<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Expires" content="Fri, Jan 01 1900 00:00:00 GMT">
<meta http-equiv="Pragma" content="no-cache">
<meta http-equiv="Cache-Control" content="no-cache">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
<meta http-equiv="Lang" content="en">
<link rel="shortcut icon" href="/img/favicon.png" type="image/png">
<title><?=$siteTitle?></title>
<link rel="stylesheet" type="text/css" href="/css/bootstrap-responsive.min.css">
<link rel="stylesheet" type="text/css" href="/css/bootstrap.min.css">
<link rel="stylesheet" type="text/css" href="/css/jquery-ui.min.css">
<link rel="stylesheet" type="text/css" href="/css/main.css">
<script type="text/javascript" src="/js/jquery-3.1.1.min.js"></script>
<script type="text/javascript" src="/js/jquery-ui.min.js"></script>
<script type="text/javascript" src="/js/bootstrap.min.js"></script>
</head>
<body>
<?php
    echo \Framework\html::render('error_list', ['message' => \App\App::$message]);
?>
<h1>База управления студентами</h1>
<div class="container-fluid">
<div class="row-fluid">
    <div class="span10">
    <div class="navbar">
      <div class="navbar-inner">
        <a class="brand" href="#">Действия</a>
        <ul class="nav">
          <li class="active"><a href="/students/list">Список</a></li>
          <li><a href="/students/new">Добавить</a></li>
        </ul>
      </div>
    </div>
      <?php
        if( ! empty($subTemplateHtml)){
            echo $subTemplateHtml;
        }
      ?>
    </div>
</div>


</body>
</html>
