<?php
    if(empty($students)):
        ?>
        <div class="alert">
            База студентов пуста
        </div>
        <?php
    else: ?>
<table class="table table-bordered table-striped table-hover">
<tr>
    <th>ID</th>
    <th>Имя</th>
    <th>Фамилия</th>
    <th>Пол</th>
    <th>Возраст</th>
    <th>Группа</th>
    <th>Факультет</th>
    <th><i class="icon-tasks"></i></th>
</tr>
    <?php
        foreach ($students as $student){
            echo \Framework\html::render('student_item', ['student' => $student]);
        }
    ?>
</table>
<?php
    endif;